services:
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
    - webapp

  webapp:
    build: ./webapp
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    depends_on:
    - redis
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  redis-data: